[package]
name = "goki"
version = "0.1.0"
description = "Goki cross-platform desktop companion"
authors = ["Goki"]
edition = "2021"

[lib]
name = "goki_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
dirs = "5.0"
global-hotkey = "0.6"
ssh2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri-plugin-dialog = "2"
sysinfo = "0.30"
tauri = { version = "2.0.0", features = ["macos-private-api", "tray-icon"] }
walkdir = "2.5"
zip = { version = "0.6", default-features = false, features = ["deflate"] }
